apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-agent-dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: trading-intelligence-agent
    newTag: latest

patchesStrategicMerge:
  - configmap-patch.yaml
